CREATE TABLE URL (ID BIGINT IDENTITY NOT NULL, CREATED DATE, DELETED DATE, STATUS INTEGER, STATUSUPDATED DATE, TYPE VARCHAR(20), UPDATED DATE, URL VARCHAR(1024), PRIMARY KEY (ID));

--ALTER TABLE FITTING ADD CONSTRAINT FK_FITTING_HEARINGAID_ID FOREIGN KEY (HEARINGAID_ID) REFERENCES HEARINGAID (ID);
