CREATE TABLE URL (ID IDENTITY NOT NULL, CREATED DATE, DELETED DATE, INSTANCE VARCHAR, STATUS INTEGER, STATUSUPDATED DATE, TYPE VARCHAR(20), UPDATED DATE, URL VARCHAR(1024), PRIMARY KEY (ID));
CREATE TABLE METADATA (ID IDENTITY NOT NULL, METAKEY VARCHAR, METAVALUE VARCHAR, PRIMARY KEY (ID));
CREATE TABLE Url_EXCLUDEURLS (Url_ID BIGINT, EXCLUDEURLS VARCHAR);
CREATE TABLE Url_LIMITURLS (Url_ID BIGINT, LIMITURLS VARCHAR);
CREATE TABLE URL_METADATA (Url_ID BIGINT NOT NULL, metadata_ID BIGINT NOT NULL, PRIMARY KEY (Url_ID, metadata_ID));
ALTER TABLE Url_EXCLUDEURLS ADD CONSTRAINT FK_Url_EXCLUDEURLS_Url_ID FOREIGN KEY (Url_ID) REFERENCES URL (ID);
ALTER TABLE Url_LIMITURLS ADD CONSTRAINT FK_Url_LIMITURLS_Url_ID FOREIGN KEY (Url_ID) REFERENCES URL (ID);
ALTER TABLE URL_METADATA ADD CONSTRAINT FK_URL_METADATA_Url_ID FOREIGN KEY (Url_ID) REFERENCES URL (ID);
ALTER TABLE URL_METADATA ADD CONSTRAINT FK_URL_METADATA_metadata_ID FOREIGN KEY (metadata_ID) REFERENCES METADATA (ID);
