ALTER TABLE `crawl` CHANGE `_ID` `ID` BIGINT( 20 ) NOT NULL;

ALTER TABLE `metadata` CHANGE `_ID` `ID` BIGINT( 20 ) NOT NULL ,
CHANGE `_METADATAVALUE` `METADATAVALUE` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
CHANGE `_METADATAKEY` `METADATAKEY` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 

ALTER TABLE `partner` CHANGE `_ID` `ID` BIGINT( 20 ) NOT NULL ,
CHANGE `_SHORTNAME` `SHORTNAME` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
CHANGE `_NAME` `NAME` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `provider` CHANGE `_ID` `ID` BIGINT( 20 ) NOT NULL ,
CHANGE `_SHORTNAME` `SHORTNAME` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
CHANGE `_NAME` `NAME` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ;

ALTER TABLE `url` CHANGE `_ID` `ID` BIGINT( 20 ) NOT NULL ,
CHANGE `_UPDATED` `UPDATED` DATETIME NULL DEFAULT NULL ,
CHANGE `_CREATED` `CREATED` DATETIME NULL DEFAULT NULL ,
CHANGE `_STATUSUPDATED` `STATUSUPDATED` DATETIME NULL DEFAULT NULL ,
CHANGE `_URL` `URL` VARCHAR( 1024 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
CHANGE `_DELETED` `DELETED` DATETIME NULL DEFAULT NULL ,
CHANGE `_STATUS` `STATUS` INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE `url_log` CHANGE `_ID` `ID` BIGINT( 20 ) NOT NULL ,
CHANGE `_UPDATED` `UPDATED` DATETIME NULL DEFAULT NULL ,
CHANGE `_CREATED` `CREATED` DATETIME NULL DEFAULT NULL ,
CHANGE `_STATUSUPDATED` `STATUSUPDATED` DATETIME NULL DEFAULT NULL ,
CHANGE `_URL` `URL` VARCHAR( 2048 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
CHANGE `_STATUS` `STATUS` INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE `url_metadata` CHANGE `_metadatas__ID` `metadatas__ID` BIGINT( 20 ) NOT NULL;